In [34]:
import copy
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import nltk
from nltk.corpus import stopwords 

In [12]:
# data_path = '/Users/zhanghan/mygithub/nlp-beginner/task1-sentiment-analysis-on-movie-reviews/train.tsv'
# df = load_data(data_path)
# sentences = df['Phrase']

## test

In [63]:
data_t = np.array(pd.read_csv('/Users/zhanghan/mygithub/nlp-beginner/task1-sentiment-analysis-on-movie-reviews/train.tsv',
                            sep='\t', header=0, nrows=5))
# X_text = df_t[?]#取出phrase列

print(df_t)
print('---')
print(sentences_t)
# print(len(sentences_t))
print('---')
print(data_t[0][2])


[[1 1
  'A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .'
  1]
 [2 1
  'A series of escapades demonstrating the adage that what is good for the goose'
  2]
 [3 1 'A series' 2]
 [4 1 'A' 2]
 [5 1 'series' 2]]
---
[[1 1
  'A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .'
  1]
 [2 1
  'A series of escapades demonstrating the adage that what is good for the goose'
  2]]
---
A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .


## load data (fin)

In [15]:
def load_data(data_path):
    '''load data from tsv file'''
    df = pd.read_csv(data_path, sep='\t', header=0, index_col='id')
    return np.array(df)

## visualize data

In [16]:
def visualize_data(data):#还可以改改 或者不写也行
    '''visualize original data'''
    
    return 1

## clean text (fin)

In [17]:
def remove_stopword(data_orig):
    '''
    remove stopwords in the wordlist
    
    data: array
    return an array
    '''
    data_filtered = data_orig.copy()   
    for i in range(data_orig.shape[0]):# 通过遍历修改data[i][2]的字符串
        filtered_words = [word.lower() for word in data_orig[i][2].split() if word not in stopwords.words('english')]
        l = ' '.join(filtered_words)
        data_filtered[i][2] = ' '.join(filtered_words) 
    return data_filtered


# test
d = np.array([[1,1,'A series of escapades demonstrating the a',1],
               [2,1, 'A series of escapades demonstrating the adage that what is good for the goose', 2],
               [3, 1, 'A series' ,2],
               [4, 1, 'A', 2],
               [5, 1, 'series', 2]])
d_f = remove_stopword(d)
d_f

array([['1', '1', 'a series escapades demonstrating', '1'],
       ['2', '1', 'a series escapades demonstrating adage good goose',
        '2'],
       ['3', '1', 'a series', '2'],
       ['4', '1', 'a', '2'],
       ['5', '1', 'series', '2']], dtype='<U77')

## make dictionary=tokenize

In [19]:
# 之后要把这里的data改成X，不要整个data进入
def make_dict_bow(data_filtered, text_col=2):
    '''
    make a bow dictionary based on all the words in the text
    return a set that contains a word list mapped with numbers
    
    data: filtered data with all columns
    text_col: text column index
    '''
    # make a non-repetitive word set
    word_set = set()
    for row in data_filtered:
        for word in row[text_col].split():
            word_set.add(word) # ('a','b')
            
    # map each string with an index number
    word_size = len(word_set)
    dict_bow = dict(zip(word_set,range(word_size))) # {'a':0,'b':1}
                    
    return dict_bow

                    
def make_dict_ng(data_filtered, text_col=2, ngram = 3):
    '''
    make a n-gram dict
    
    data_filtered: sentences array
    ngram: n-gram number
    '''
    # "在一般的文本分类任务中,N 取 3 就足够了
    
    # make a non-repetitive word set 
    word_set = set()
    for row in data_filtered:
        wordlist_row = row[text_col].split()
        for n in range(ngram):
            for i in range(len(wordlist_row) - n):
                word_set.add(' '.join(wordlist_row[ i : i + ngram ])) # ('a','a b')
        
    # map each string with an index number
    word_size = len(word_set)
    dict_ng = dict(zip(word_set,range(word_size))) # {'a':0,'b':1}
    
    return dict_ng

# test passed!
# d2 = np.array([['1', '1', 'a series escapades demonstrating', '1'],
#        ['2', '1', 'a series escapades demonstrating adage good goose',
#         '2'],
#        ['3', '1', 'a series', '2'],
#        ['4', '1', 'a', '2'],
#        ['5', '1', 'series', '2']], dtype='<U77')
# print('d2_bow: ', make_dict_bow(d2,2))
# print('d2_ng: ', make_dict_ng(d2))

## data -> vec

In [21]:
def vectorize_bow(data_filtered, dict_bow, text_col=2): 
    '''
    data_filtered: array, filtered data
    return an array of vectorized features
    '''
    features_bow = np.zeros((data_filtered.shape[0],len(dict_bow)))
    for i in range(data_filtered.shape[0]): # array中的每个句子：
        phrase_i = data_filtered[i][text_col]
        wordlist = phrase_i.split()
        for word in wordlist: # for每个句子中的每个单词：
            if word in dict_bow:# if这个单词在字典中：
                j = dict_bow[word]
                features_bow[i][j] += 1 # features对应dict相同index的位置变为1
    return features_bow


def vectorize_ng(data_filtered, dict_ng, text_col=2, ngram=3): # N-gram：ng_vectorizer.transform(corpus)
    '''
    data_filtered: array, filtered data
    return an array of vectorized features
    '''
    features_ng = np.zeros((data_filtered.shape[0],len(dict_ng)))
    for i in range(data_filtered.shape[0]): # for array中的每个句子
        phrase_i = data_filtered[i][text_col]
        wordlist = phrase_i.split()
        for n in range(ngram):
            for index in range(len(wordlist)-n): # for每个句子中的每个word_ng：
                word_ng = ' '.join(wordlist[ index : index + n+1 ])
                # print(index, word_ng)
                if word_ng in dict_ng: # if这个word_ng在字典中：
                    j = dict_ng[word_ng]
                    features_ng[i][j] += 1 # features对应dict相同index的位置+1
    return features_ng

# test passed!
a3 = np.array([['1', '1', 'a series escapades demonstrating', '1'],
       ['2', '1', 'a series escapades demonstrating adage good goose',
        '2'],
       ['3', '1', 'a series', '2'],
       ['4', '1', 'a', '2'],
       ['5', '1', 'series', '2']], dtype='<U77')
print('original data: \n',a3,'\n')

dict_bow_t = make_dict_bow(a3,2)
dict_ng_t = make_dict_ng(a3)

f_t_bow = vectorize_bow(a3, dict_bow_t)
f_t_ng = vectorize_ng(a3, dict_ng_t)
print(dict_bow_t, '\n', '*'*25, '\n',f_t_bow)
print('\n')
print(dict_ng_t, '\n', '*'*25, '\n', f_t_ng)

original data: 
 [['1' '1' 'a series escapades demonstrating' '1']
 ['2' '1' 'a series escapades demonstrating adage good goose' '2']
 ['3' '1' 'a series' '2']
 ['4' '1' 'a' '2']
 ['5' '1' 'series' '2']] 

{'adage': 0, 'demonstrating': 1, 'good': 2, 'escapades': 3, 'a': 4, 'goose': 5, 'series': 6} 
 ************************* 
 [[0. 1. 0. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


{'a series': 0, 'demonstrating': 1, 'good goose': 2, 'series escapades demonstrating': 3, 'a': 4, 'a series escapades': 5, 'goose': 6, 'series': 7, 'escapades demonstrating': 8, 'adage good goose': 9, 'escapades demonstrating adage': 10, 'demonstrating adage good': 11} 
 ************************* 
 [[1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


array([[0., 1., 0., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## train (get model+gradient descent)

cost function:

$$
\begin{aligned}
\mathcal{R}(w)
	&=-\frac{1}{N}\displaystyle \sum^{N}_{n=1}\mathcal{L}(y^{(n)},\hat y^{(n)})\\
	&=-\frac{1}{N}\displaystyle \sum^{N}_{n=1}{\left(y^{(n)}\right)^T\log \hat y^{(n)}\\}
\end{aligned}\tag{3.6}
$$

gradient:

$$
\frac{\partial \mathcal{R}(w)}{\partial w}=-\frac{1}{N}\sum_{n=1}^{N}{x^{(n)}(y^{(n)}-\hat y^{(n)})}\tag{3.7}
$$


In [70]:
def softmax(z):
    '''compute the softmax output of z = wx + b'''
    ez = np.exp(z)
    sm = ez / np.sum(ez)
    return sm
    

def compute_cost(X, y, W, b):
    '''
    compute the total cost of given parameters
    
    Args:
        X (array, (m,n)): m training examples, n features
        y (array, (m,))
        W (array, (n,))
    '''
    
    m,n = X.shape
    y_hat = np.dot(X,W) + b
    cost = np.dot(y, np.log(y_hat)) * (-1) / m
    
    return cost


def train(X_train, y_train, W_init, b_init, epochs, alpha, gd='mini-batch'):
    '''
    learn the parameters
    
    Args:
        X_train (array, (m,n)): m for training examples, n for features
        y_train (array, (m,))
        W_init (array, (n,))
        alpha (float): learning rate
        epochs (int): 
        gd (string): method for gradient descent. 'batch', 'stochastic' or 'mini-batch'
    Return
        W (array, (n,)): parameters
        cost_hist (list): a list of cost for plotting
    '''
    
    m,n = X_train.shape
    cost_hist = []
    W = copy.deepcopy(W_init)
    
    
    if gd == 'batch':
        batch_size = m # 每个batch里的example数
        itertimes = 1
    if gd == 'stochastic':
        batch_size = 1
        itertimes = m
    if gd == 'mini-batch':
        batch_size = 64 # temp
        itertimes = m // batch_size + 1 # 1 for the non-full batch
        
    for e in range(epochs):
        
        #shuffle
        arr_XY = list(zip(X_train, y_train))
        np.random.shuffle(arr_XY)
        X_sf, y_sf = zip(*arr_XY)
        X_sf, y_sf = np.array(X_sf),np.array(y_sf)
        
        # update parameters after iterating over all exmpls in one batch. mini-batch by default.
        # BGD iterates over all exmpls at one time; SGD iterates over one exmpl at a time
        for k in range(itertimes):# for every batch（bgd has one batch, sgd has m ones, mini has itertimes batches）

            # compute gradient
            dj_dw = np.zeros((n,))                            #(n,)
            dj_db = 0.                                        #scalar
            if k == itertimes - 1: # if the last batch
                batch_size = m % 64 # temp
            for i in range(batch_size):# for every training example in the batch
                i_batch = i + k * batch_size
                y_hat_i = softmax(np.dot(X_sf[i_batch],W)+b_init)       #(n,)(n,)=scalar
                err_i  = y_hat_i  - y_sf[i_batch]                       #scalar
                # print('W shape:',W.shape)
                # print(type(y_hat_i))
                for j in range(n):
                    dj_dw[j] = dj_dw[j] + err_i * X_sf[i_batch,j]       #scalar
                dj_db += err_i
            dj_dw = dj_dw/m                                             #(n,)       
            dj_db = dj_db/m  

            # gradient descent
            W = W - alpha * dj_dw
            b_init = W - alpha * dj_db
            
            # Save cost at each iteration (of a batch)
            cost_hist.append(compute_cost(X_sf, y_sf, W, b_init) )
            
            # print cost at an interval of 1000 iterations
            if k % 1000 == 0:
                print(f"Iteration {k:4}: Cost {float(cost_hist[-1]):8.2f}")
                
    return W, b_init, cost_hist


# test
m,n = X_train_t.shape
X_train_t = f_t_bow
y_train_t = np.array([d_f[i, 3] for i in range(X_train_t.shape[0])], dtype = int)
W_init = np.zeros((n,))
train(X_train_t, y_train_t, W_init, b_init=0, epochs=2, alpha=0.1, gd='mini-batch')

#接下来确认一下compute cost里的维度
# w_t, b_t, cost_hist_t

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

7


ValueError: setting an array element with a sequence.

### prediction

In [9]:
import numpy as np
a_x = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
a_y = np.array(['a','b','c','d','e'])

a_xy = list(zip(a_x,a_y))
np.random.shuffle(a_xy)
a_xy

[(array([2, 2, 2]), 'c'),
 (array([1, 1, 1]), 'b'),
 (array([0, 0, 0]), 'a'),
 (array([4, 4, 4]), 'e'),
 (array([3, 3, 3]), 'd')]

In [ ]:
def save_data():



def accuracy():

def plot_result():