# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

### 个人reference：

[numpy doc](https://www.numpy.org.cn/user/basics/indexing.html#%E7%B4%A2%E5%BC%95%E5%A4%9A%E7%BB%B4%E6%95%B0%E7%BB%84)

[python numpy详解](https://zhuanlan.zhihu.com/p/77211227)


In [42]:
# 置顶：关于高级切片和索引

y = np.arange(35).reshape(5,7)
print(y,'\n')
print('切片--y[1:5:2,::3]:','\n',y[1:5:2,::3],'\n')

# 情况1:
# 如果索引数组具有【匹配的形状】，并且索引数组的【每个维度都有一个索引数组】，
# 则结果数组具有与索引数组相同的形状，并且值对应于每个索引的索引集在索引数组中的位置。
print('情况1--y[[0,2,4], [0,1,2]]:','\n',y[[0,2,4], [0,1,2]]) 
    # 分别索引：y [0,0]（[左边第1个,右边第1个]） y [2,1][左边第2个,右边第2个]） y [4,2]
print('情况1--y[[0,1],[2,2]]:','\n',y[[0,1],[2,2]])
print('*'*25)

# 情况2: 如果索引数组【形状不匹配】，则会引发异常 如y[np.array([0,2,4]), np.array([0,1])]

# 情况3: 广播机制允许索引数组【与其他索引的标量组合】，结果是标量值用于索引数组的所有相应值，如
print('情况3--y[[0,2,4], 1]:','\n',y[np.array([0,2,4]), 1])
    # 行为第0，2，4；列为1
print('情况3--y[[0, 1], 1:3]:','\n',y[[0, 1], 1:3])
    # [0,1]是取第0行和第1行，然后[1,3)列
print('*'*25)

# 情况4:【仅使用索引数组】对数组进行部分索引。
# 结果为构造一个新数组，其中索引数组的每个值选择一行，结果数组具有结果形状（索引元素的数量，行的大小）。
print('情况4--y[[0,2,4]]:','\n',y[[0,2,4]])
print('*'*25)

print(y[[0,1],[2,2]])

# 总结一下：
# 看到花式索引，1）判断【索引数组形状是否匹配】，比如[2,1]和[3,4]、[1,2,0]和[3,2,2]；
# 且每个维度都有一个索引数组，比如2D array需要有2个数组。有的话就是【数组对应位置成组作为索引】
# 2）其他情况，默认逗号左是行的条件，右是列的条件

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]] 

切片--y[1:5:2,::3]: 
 [[ 7 10 13]
 [21 24 27]] 

情况1--y[[0,2,4], [0,1,2]]: 
 [ 0 15 30]
情况1--y[[0,1],[2,2]]: 
 [2 9]
*************************
情况3--y[[0,2,4], 1]: 
 [ 1 15 29]
情况3--y[[0, 1], 1:3]: 
 [[1 2]
 [8 9]]
*************************
情况4--y[[0,2,4]]: 
 [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
*************************
[2 9]


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [47]:
print(np.__version__)
np.show_config()

1.23.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [50]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# pass

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# pass

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [53]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [55]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [60]:
X = np.arange(10)
Y = X[::-1]
print(Y)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [64]:
X = np.arange(9)
Y = X.reshape(3,3)
Y

# 可以直接np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [68]:
X = np.array([1,2,0,0,4,0])
Y = X[X != 0]
Y

# 答案是np.nonzero([1,2,0,0,4,0])

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [70]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [75]:
# 没写出来

np.random.random((3,3,3))

array([[[0.15261623, 0.28804751, 0.51387784],
        [0.9178356 , 0.14555715, 0.15846915],
        [0.88328718, 0.80407738, 0.75796255]],

       [[0.63178879, 0.63995347, 0.44707151],
        [0.76668239, 0.05925587, 0.5182576 ],
        [0.92067866, 0.59077298, 0.54353814]],

       [[0.60741507, 0.59304447, 0.74859333],
        [0.00671167, 0.55534593, 0.76030714],
        [0.94494246, 0.04267225, 0.38381651]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [82]:
X = np.random.random((10,10))
a = X.max()
b = X.min()
print(a,b)

0.9988500741452561 0.005065261322741099


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [85]:
X = np.random.random((3,10))
X.mean()

0.5333704113069113

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [86]:
# 不会
X = np.ones(16).reshape(4,4)
X[1:-1,1:-1] = 0
X

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [96]:
# 不会
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [98]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
np.nan in set([np.nan]),
0.3 == 3 * 0.1)

nan False False nan True False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [103]:
X = np.eye(5)
X[1,0], X[2,1], X[3,2], X[4,3] = 1,2,3,4
print(X)

# 聪明奇妙的写法
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [114]:
X = np.zeros(64,dtype=int)
X[::2]=1
X.reshape((8,8))# note: 不是(8,8)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [115]:
# 不会
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
# 不会
>>> b = np.array([[1, 2], [3, 4]])
>>> np.tile(b, 2) #沿X轴复制2倍
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])
>>> np.tile(b, (2, 1))#沿X轴复制1倍（相当于没有复制），再沿Y轴复制2倍
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [116]:
# 不会 z-score标准化：（x-μ）/σ 
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.94784466 -1.03451019  0.16125821  0.83019408  0.27883648]
 [ 1.34262969  1.25166228 -1.42607852 -1.57341522 -0.1816835 ]
 [-1.1538476   0.36247965  0.38735677 -0.74533384  1.64602138]
 [-1.10291081 -0.5570816  -0.42673452  0.6771735   0.98414603]
 [ 1.61867917 -0.95546352 -1.44987467 -0.51983947  0.63849157]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [117]:
# pass

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [121]:
A = np.random.random((5,3))
B = np.random.random((3,2))
# print(A,B)
C = np.matmul(A,B)
print(C)

#alternative
D = A @ B # == np.dot()
print(D)

[[1.3042694  1.60900391]
 [1.06608954 1.18613705]
 [0.89495818 1.30872369]
 [0.990959   1.21349387]
 [0.84508069 0.91637721]]
[[1.3042694  1.60900391]
 [1.06608954 1.18613705]
 [0.89495818 1.30872369]
 [0.990959   1.21349387]
 [0.84508069 0.91637721]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [132]:
A = np.arange(10)
A[ (A>3) & (A<8) ] = (-1)* A[ (A>3) & (A<8) ] # 注意加括号
A

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [134]:
# ？
print(sum(range(5),-1))
print(range(5),-1)
from numpy import *
print(sum(range(5),-1))
print(range(5),-1)

10
range(0, 5) -1
10
range(0, 5) -1


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [135]:
print(np.array(0) / np.array(0))

nan


/var/folders/dx/8f_bwyx942x14p_nywnn6_zw0000gn/T/ipykernel_25670/4120864939.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
# pass

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# pass

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# pass

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
# pass

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
# pass

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [137]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)

[1. 4. 4. 9. 6. 1. 5. 2. 9. 9.]
[1. 4. 4. 9. 6. 1. 5. 2. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [139]:
def gener():
    for x in range(10):
        yield x
        
np.fromiter(gener(),dtype = int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [142]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [149]:
X = np.random.random(10)
X.sort()
X

array([0.16814075, 0.30129858, 0.32194269, 0.33075364, 0.48986478,
       0.57584708, 0.66488479, 0.72686028, 0.86643506, 0.99215978])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
# 后面很多是fancy的用法 等需要用到再学吧

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [136]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)